allowBuilds:
  '@biomejs/biome': true
  '@mercuryworkshop/scramjet': true
  bufferutil: true
  esbuild: true
  sharp: true
  sqlite3: true
onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@mercuryworkshop/scramjet'
  - bufferutil
  - esbuild
  - sharp
  - sqlite3
  - utf-8-validate
